### ISSUE TITLE
systemName Property of FakeFtpServer Does Not Match the Chosen FileSystem

### ISSUE THREAD

**Issue by pbtura** [dx42/MockFtpServer#15]
When setting up a FakeFtpServer, the systemName property defaults to 'WINDWS'. If a non-windows FileSystem is assigned during setup, the systemName property is not updated and any calls involving the SYST command will potentially return incorrect values. It is possible to fix this by explicitly setting the systemName property, but it is not clear from the documentation that this is required.

Suggestion: if this is intended behavior, then the documentation needs to mention the need to set SystemName and outline what the valid values are.

**Comment by chrismair** [comment]
FakeFtpServer will now use the *systemName* from the configured FileSystem for the SYST command, but can be overridden by setting the *systemName* property on FakeFtpServer.
