### ISSUE TITLE
Provide REST API to FTP Server

### ISSUE THREAD

**Issue by jmizv** [dx42/MockFtpServer#24]
## Scenario
I have several microservices implemented in Java Spring Boot. One of these is putting files to a FTP Server based on the interaction with the other services. I want to test this scenario but because my test framework ([Karate](https://github.com/karatelabs/karate)) can do REST API call best, I would be happy to access the files and folders in the MockFtpServer also via REST API.

For example, I certainly need to check whether some files exists and to download them via REST API.

Is this on your roadmap?

For inspiration, I'm also using [MailDev](https://github.com/maildev/maildev/blob/master/docs/rest.md) as an Mock MailServer and it provides an REST API which I use to see whether some mails were send from my microservices.

**Comment by chrismair** [comment]
No, nothing like that is on the roadmap.
